"""clear existing migrations

Revision ID: 20b3c23c0eeb
Revises: 770371e7ca05
Create Date: 2023-11-25 22:18:25.294942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b3c23c0eeb'
down_revision = '770371e7ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_bus_details')
    op.drop_table('add_bus_details')
    op.drop_table('bus_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('starting_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ending_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_seats', sa.INTEGER(), nullable=False),
    sa.Column('stops', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ticket_charge', sa.FLOAT(), nullable=False),
    sa.Column('time_duration', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_bus_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bus_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('starting_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ending_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_seats', sa.INTEGER(), nullable=False),
    sa.Column('stops', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ticket_charge', sa.FLOAT(), nullable=False),
    sa.Column('time_duration', sa.VARCHAR(length=50), nullable=False),
    sa.Column('departure_time', sa.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_bus_details',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('starting_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ending_point', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_seats', sa.INTEGER(), nullable=False),
    sa.Column('stops', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ticket_charge', sa.FLOAT(), nullable=False),
    sa.Column('time_duration', sa.VARCHAR(length=50), nullable=False),
    sa.Column('bus_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('departure_time', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
