"""initial migration

Revision ID: 628d54376ef7
Revises: 3478432d68d6
Create Date: 2023-11-25 23:51:25.204525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628d54376ef7'
down_revision = '3478432d68d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_availability', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('add_bus', schema=None) as batch_op:
        batch_op.drop_column('seat_availability')

    # ### end Alembic commands ###
